### ISSUE TITLE
Unexpected props drop

### ISSUE THREAD

**Issue by eugeneilyin** [heyymarco/postcss-merge-rules-plus#1]
Hi @heyymarco, thanks for the CSS props merging attempts.
## Minimal example to reproduce
`node test.cjs`
```js
const postcss = require('postcss')
const postcssMerge = require('postcss-merge-rules-plus').default
const css = `
html { }
html {
  cursor: default;
  line-height: 1.5;
  -moz-tab-size: 4;
    -o-tab-size: 4;
       tab-size: 4;
  -webkit-tap-highlight-color: transparent;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
  word-break: break-word;
}`
postcss([postcssMerge()]).
  process(css, { from: undefined }).
  then(({ css }) => console.log(css))
```

I have the next console output:
```css
html {
  cursor: default;
  -moz-tab-size: 4;
       tab-size: 4;
  -ms-text-size-adjust: 100%;
  word-break: break-word }   
```

Please check why the rest of the CSS props were droppped (like `line-height`, or `-o-tab-size`).

`postcss`: `8.2.8`
`postcss-merge-rules-plus`: `1.0.1`
`node --version`: `v14.16.0`
